name = "GeneticAlgorithms"
uuid = "a19e135c-5e69-4121-b36b-f716310c090d"
version = "1.0.1"
authors = ["AlanFreed <alan.d.freed@proton.me>"]

[deps]
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
PhysicalFields = "ecb0663d-aa47-424e-b5ff-03a0dca9671a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Xicor = "77194b58-d7c3-46dd-b530-0e56265cadd8"

[compat]
PhysicalFields = "1.3.1"
Plots = "1.41.4"
