name = "CubicSplines"
uuid = "2555dc27-9595-4c2f-aa4a-fc7d9c409629"
version = "0.1.3"
authors = ["Alan Freed <alan.d.freed@proton.me>"]

[deps]
BandedMatrices = "aae01518-5342-5314-be14-df237901396f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Plots = "1.41.4"
